### ISSUE TITLE
api.dart Errors

### ISSUE THREAD

**Issue by DatBirbDude** [greenturtle537/CommunityConnect#12]
Recent commits to the main branch have left api.dart with 9 errors, making running the application difficult. I have attempted fixes to these errors to allow myself to work on the front end, but would appreciate official fixes from a backend developer.

**Comment by DatBirbDude** [comment]
I believe I have identified and fixed the issues and will be committing them to the VSAGTEB branch. If these fixes are incorrect, DO NOT approve my next pull request and fix these issues before merging.

**Comment by greenturtle537** [comment]
Please note that your changes have not been mirrored upstream as of this post. I recommend you pull from latest main. The api.dart file should compile safely.

**Comment by greenturtle537** [comment]
Will post repair build shortly

**Comment by DatBirbDude** [comment]
I apologize for not mirroring my changes upstream, abruptly after my last comment I realized I had to take my dog on a walk and quickly left my workstation without pushing the changes. I will pull from main when I return to my workstation.

**Comment by DatBirbDude** [comment]
I have now officially opened a pull request with the fixes to api.dart

**Comment by greenturtle537** [comment]
Closed error. Awaiting closure on pull request.
