### ISSUE TITLE
Platform releases.

### ISSUE THREAD

**Issue by greenturtle537** [greenturtle537/CommunityConnect#14]
What platforms will we be targeting for release? Please suggest with reasoning.

**Comment by DatBirbDude** [comment]
I was under the impression that, after incredible lobbying on your part, we would be releasing as a web app. Despite this, our front end code has been manufactured in a way that will likely allow it to be built as an executable as well. Either way, I believe that we should only make an official prior to the Summer of 2024, as our upcoming March 14th deadline does not require and will likely not benefit from having an official release available.

**Comment by greenturtle537** [comment]
OK. I'll modify our milestones accordingly.
