### ISSUE TITLE
Can't connect to glitchtech.top

### ISSUE THREAD

**Issue by DatBirbDude** [greenturtle537/CommunityConnect#18]
Any function in api.dart that requires interacting with the server appears to give the same error - ClientException: XMLHttpRequest error.

**Comment by DatBirbDude** [comment]
I am unsure whether or not this is only a problem on my end.

**Comment by greenturtle537** [comment]
Please post related error logs for debugging

**Comment by greenturtle537** [comment]
Issue resolved on server-side.
