### ISSUE TITLE
Laremy change

### ISSUE THREAD

**Issue by greenturtle537** [greenturtle537/CommunityConnect#5]
In reference to:
edbeb50: john -> laremy

Laremy is an L name. Please find a better one.

**Comment by Tartarus6** [comment]
Laremy is a W name. This change was simply for the better of the app.

**Comment by greenturtle537** [comment]
Laremy puts the L in Laremy. Re-opened

**Comment by greenturtle537** [comment]
@Tartarus6 Laremy will be removed before public release. Todo: Close on removal

**Comment by greenturtle537** [comment]
@Tartarus6 Laremy is now in main-stable-upstream-release-alpha-demo-public-launch. Will relabel.
